import type { ClientConfig } from "../types.js";
import { DEFAULT_BRAND_ASSETS } from "../types.js";

export function generateClientPackModule(cfg: ClientConfig): string {
  const assets = cfg.brand.assets ?? DEFAULT_BRAND_ASSETS;
  const payload = {
    name: cfg.brand.name,
    shortName: cfg.brand.shortName,
    tagline: cfg.brand.tagline ?? "",
    hashtag: cfg.brand.hashtag ?? "",
    legalEntityName: cfg.brand.legalEntityName ?? "",
    copyrightText: cfg.brand.copyrightText ?? "",
    contactName: cfg.brand.contactName,
    contactRole: cfg.brand.contactRole,
    contactBio: cfg.brand.contactBio ?? [],
    notifyEmail: cfg.brand.notifyEmail,
    phone: cfg.brand.phone,
    phoneHref: cfg.brand.phoneHref,
    social: cfg.brand.social ?? {},
    venues: cfg.brand.venues,
    origin: cfg.brand.origin,
    appBase: cfg.brand.appBase,
    assets,
    themeClass: cfg.style.themeClass,
    fonts: cfg.style.fonts,
    primary: cfg.style.primary ?? cfg.style.accent,
    secondary: cfg.style.secondary ?? cfg.style.muted,
    ink: cfg.style.ink,
    paper: cfg.style.paper,
    accent: cfg.style.accent,
    locale: cfg.locale.locale,
    timeZone: cfg.locale.timeZone,
    currency: cfg.locale.currency,
    seasonModel: cfg.locale.seasonModel ?? { mode: "manual" as const },
    roleLabels: cfg.language?.roleLabels ?? {
      admin: "Admin",
      trainer: "Trainer",
      member: "Member",
    },
    paymentInstructions: cfg.language?.paymentInstructions ?? "",
    classCatalog: cfg.language?.classCatalog ?? [],
    packageIdentity: cfg.infra.packageIdentity ?? {
      npmRoot: "studio",
      sharedAlias: "@studio/shared",
    },
    signInPath: cfg.infra.signInPath ?? "signin/",
  };

  return `/* Generated by @whitelabel/pivot-kit — import from marketing + apps */
/* Values come only from client.config.json intake — no themed toolkit defaults. */
export const brand = ${JSON.stringify(payload, null, 2)} as const;

export type BrandPack = typeof brand;

export function getRoleDisplayName(claim: string): string {
  return (brand.roleLabels as Record<string, string>)[claim] ?? claim;
}

export default brand;
`;
}
