import type { ClientConfig } from "../types.js";

function signInPath(cfg: ClientConfig): string {
  return cfg.infra.signInPath ?? "signin/";
}

function callableOrigins(cfg: ClientConfig): string {
  const list =
    cfg.infra.callableOrigins?.length ?
      cfg.infra.callableOrigins
    : [
        cfg.brand.origin,
        "http://localhost:5173",
        "http://127.0.0.1:5173",
      ];
  return list.join(",");
}

export function generateEnvFiles(cfg: ClientConfig): {
  rootExample: string;
  appsExample: string;
  functionsExample: string;
} {
  const signInUrl = `${cfg.brand.origin}${cfg.brand.appBase}${signInPath(cfg)}`;

  const rootExample = `# Generated by @whitelabel/pivot-kit — marketing / root Vite
# Fill values; never commit secrets. Toolkit is self-contained; no host asset paths.
VITE_FIREBASE_API_KEY=
VITE_FIREBASE_AUTH_DOMAIN=${cfg.infra.firebaseProjectId}.firebaseapp.com
VITE_FIREBASE_PROJECT_ID=${cfg.infra.firebaseProjectId}
VITE_FIREBASE_APP_ID=
VITE_FORM_ENDPOINT=
VITE_BASE=/
VITE_CLIENT_ORIGIN=${cfg.brand.origin}
`;

  const appsExample = `# Generated by @whitelabel/pivot-kit — member/staff app Vite
# Fill values; never commit secrets.
VITE_FIREBASE_API_KEY=
VITE_FIREBASE_AUTH_DOMAIN=${cfg.infra.firebaseProjectId}.firebaseapp.com
VITE_FIREBASE_PROJECT_ID=${cfg.infra.firebaseProjectId}
VITE_FIREBASE_APP_ID=
VITE_FORM_ENDPOINT=
VITE_APP_BASE=${cfg.brand.appBase}
VITE_CLIENT_ORIGIN=${cfg.brand.origin}
`;

  const functionsExample = `# Cloud Functions params / secrets (names from §G1)
# Set via firebase functions:config / params / secrets — do not commit values
FORM_ENDPOINT=
FUNCTIONS_WEBHOOK_SECRET=
SIGN_IN_URL=${signInUrl}
CALLABLE_ORIGINS=${callableOrigins(cfg)}
TIME_ZONE=${cfg.locale.timeZone}
FUNCTIONS_REGION=${cfg.locale.functionsRegion}
`;

  return { rootExample, appsExample, functionsExample };
}
