import type { ClientConfig } from "../types.js";

function absUrl(origin: string, path: string): string {
  if (path.startsWith("http")) return path;
  const p = path.startsWith("/") ? path : `/${path}`;
  return `${origin}${p}`;
}

function escapeXml(s: string): string {
  return s
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;");
}

export function generateSeoPack(cfg: ClientConfig): Record<string, string> {
  const origin = cfg.brand.origin;
  const appBase = cfg.brand.appBase;
  const files: Record<string, string> = {};

  const disallowTraining = cfg.infra.aiCrawlerPolicy?.disallowTrainingBots !== false;
  const allowCitation = cfg.infra.aiCrawlerPolicy?.allowCitationBots === true;

  let robots = `# Generated by @whitelabel/pivot-kit
User-agent: *
Allow: /
Disallow: ${appBase}
Disallow: /demo/

Sitemap: ${origin}/sitemap.xml
`;
  if (disallowTraining) {
    robots += `
User-agent: CCBot
Disallow: /

User-agent: Google-Extended
Disallow: /
`;
  }
  if (allowCitation) {
    robots += `
# Citation bots: default Allow from * above; tighten per client notes if needed
`;
  }
  files["robots.txt"] = robots;

  const urls = cfg.seo.routes
    .map((r) => {
      const loc = r.path === "/" ? `${origin}/` : `${origin}${r.path}`;
      return `  <url>
    <loc>${escapeXml(loc)}</loc>
  </url>`;
    })
    .join("\n");
  files["sitemap.xml"] = `<?xml version="1.0" encoding="UTF-8"?>
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
${urls}
</urlset>
`;

  const venue = cfg.brand.venues[0];
  const jsonLd = {
    "@context": "https://schema.org",
    "@type": "LocalBusiness",
    name: cfg.brand.name,
    url: origin,
    email: cfg.brand.notifyEmail,
    telephone: cfg.brand.phone,
    image: absUrl(origin, cfg.seo.defaultOgImage),
    description: cfg.seo.siteDescription,
    address: venue
      ? {
          "@type": "PostalAddress",
          streetAddress: venue.address,
        }
      : undefined,
    geo: venue?.geo
      ? {
          "@type": "GeoCoordinates",
          latitude: venue.geo.lat,
          longitude: venue.geo.lng,
        }
      : undefined,
  };
  files["json-ld.local-business.json"] = JSON.stringify(jsonLd, null, 2) + "\n";

  for (const route of cfg.seo.routes) {
    const og = absUrl(origin, route.ogImage ?? cfg.seo.defaultOgImage);
    const canonical =
      route.path === "/" ? `${origin}/` : `${origin}${route.path}`;
    const slug =
      route.path === "/"
        ? "index"
        : route.path.replace(/^\/|\/$/g, "").replace(/\//g, "-") || "index";
    files[`meta/${slug}.html`] = `<!-- Generated meta pack for ${route.path} -->
<title>${escapeXml(route.title)}</title>
<meta name="description" content="${escapeXml(route.description)}" />
<link rel="canonical" href="${escapeXml(canonical)}" />
<meta property="og:type" content="website" />
<meta property="og:title" content="${escapeXml(route.title)}" />
<meta property="og:description" content="${escapeXml(route.description)}" />
<meta property="og:url" content="${escapeXml(canonical)}" />
<meta property="og:image" content="${escapeXml(og)}" />
<meta name="twitter:card" content="summary_large_image" />
<meta name="twitter:title" content="${escapeXml(route.title)}" />
<meta name="twitter:description" content="${escapeXml(route.description)}" />
<meta name="twitter:image" content="${escapeXml(og)}" />
<script type="application/ld+json">
${JSON.stringify(jsonLd)}
</script>
`;
  }

  if (cfg.infra.aiCrawlerPolicy) {
    files["llms.txt"] = `# ${cfg.brand.name}
> ${cfg.seo.siteDescription}

${cfg.infra.aiCrawlerPolicy.notes ?? ""}

Canonical: ${origin}/
App (noindex): ${origin}${appBase}
`;
  }

  return files;
}
