import type { ClientConfig } from "../types.js";

export function generateThemeCss(cfg: ClientConfig): string {
  const t = cfg.style;
  const cls = t.themeClass.startsWith(".") ? t.themeClass.slice(1) : t.themeClass;
  const primary = t.primary ?? t.accent;
  const secondary = t.secondary ?? t.muted;
  return `/* Generated by @whitelabel/pivot-kit — do not hand-edit; re-run wl generate */
/* Token hooks only — palette values come from Client Pack intake. */
.${cls} {
  --wl-ink: ${t.ink};
  --wl-paper: ${t.paper};
  --wl-muted: ${t.muted};
  --wl-line: ${t.line};
  --wl-accent: ${t.accent};
  --wl-primary: ${primary};
  --wl-secondary: ${secondary};
  --wl-font-display: ${JSON.stringify(t.fonts.display)}, Georgia, serif;
  --wl-font-body: ${JSON.stringify(t.fonts.body)}, system-ui, sans-serif;
  color: var(--wl-ink);
  background-color: var(--wl-paper);
  font-family: var(--wl-font-body);
}

.${cls} h1,
.${cls} h2,
.${cls} .display {
  font-family: var(--wl-font-display);
}

.${cls} a {
  color: var(--wl-accent);
}

.${cls} .wl-primary {
  color: var(--wl-primary);
}

.${cls} .wl-secondary {
  color: var(--wl-secondary);
}
`;
}
