/* Generated by @whitelabel/pivot-kit — import from marketing + apps */
/* Values come only from client.config.json intake — no themed toolkit defaults. */
export const brand = {
  "name": "Sollys",
  "shortName": "Sollys",
  "tagline": "Enable the success of others by connecting people and products",
  "hashtag": "#Sollys",
  "legalEntityName": "Sollys Freight 1978 Ltd",
  "copyrightText": "© Sollys Freight 1978 Ltd",
  "contactName": "Merv Solly",
  "contactRole": "Owner",
  "contactBio": [
    "Family-owned South Island freight, contracting, and earthmoving since 1928, with depots from Golden Bay through to Christchurch."
  ],
  "notifyEmail": "sales@sollys.co.nz",
  "phone": "+64 3 525 9843",
  "phoneHref": "tel:+6435259843",
  "social": {
    "facebook": "https://www.facebook.com/profile.php?id=61557223335051",
    "instagram": "https://www.instagram.com/sollys.nz/",
    "youtube": "https://www.youtube.com/channel/UCf_ywbETh8Bj9wqDKyezqdw"
  },
  "venues": [
    {
      "name": "Takaka Head Office",
      "address": "98A Commercial Street, Takaka 7110",
      "geo": {
        "lat": -40.8536,
        "lng": 172.8076
      }
    },
    {
      "name": "Collingwood Depot",
      "address": "Mount Burnett Road, Takaka 7110",
      "geo": {
        "lat": -40.678,
        "lng": 172.683
      }
    },
    {
      "name": "Rockville Depot",
      "address": "545 Collingwood Bainham Main Road, Rockville 7073",
      "geo": {
        "lat": -40.641,
        "lng": 172.661
      }
    },
    {
      "name": "Richmond Depot",
      "address": "32 McPherson Street, Richmond 7020",
      "geo": {
        "lat": -41.3394,
        "lng": 173.187
      }
    },
    {
      "name": "Christchurch Depot",
      "address": "9 Sir James Wattie Drive, Hornby, Christchurch 8042",
      "geo": {
        "lat": -43.5435,
        "lng": 172.525
      }
    },
    {
      "name": "Blenheim Depot",
      "address": "Riverlands Roadhouse, 3535 State Highway 1, Riverlands 7274",
      "geo": {
        "lat": -41.543,
        "lng": 174.005
      }
    }
  ],
  "origin": "https://www.sollys.co.nz",
  "appBase": "/app/",
  "assets": {
    "logoLight": "public/brand/logo-light.svg",
    "logoDark": "public/brand/logo-dark.svg",
    "favicon": "public/brand/favicon.svg",
    "appIcon": "public/brand/sollys-logo-source.png",
    "logoWidth": 160,
    "logoHeight": 32
  },
  "themeClass": "theme-sollys",
  "fonts": {
    "display": "Oswald",
    "body": "Source Sans 3",
    "source": "Google Fonts"
  },
  "primary": "#1C3D1A",
  "secondary": "#D4B20A",
  "ink": "#1C3D1A",
  "paper": "#F4F1E8",
  "accent": "#C5D44A",
  "locale": "en-NZ",
  "timeZone": "Pacific/Auckland",
  "currency": "NZD",
  "seasonModel": {
    "mode": "manual",
    "notes": "Freight runs, not studio terms."
  },
  "roleLabels": {
    "admin": "Admin",
    "trainer": "Driver",
    "member": "Client"
  },
  "paymentInstructions": "",
  "classCatalog": [],
  "packageIdentity": {
    "npmRoot": "sollys",
    "npmApps": "sollys-apps",
    "npmFunctions": "sollys-functions",
    "sharedAlias": "@sollys/shared"
  },
  "signInPath": "signin/"
} as const;

export type BrandPack = typeof brand;

export function getRoleDisplayName(claim: string): string {
  return (brand.roleLabels as Record<string, string>)[claim] ?? claim;
}

export default brand;
